version: 0.2

batch:
  fast-fail: false
  build-matrix:
    - identifier: build1
    - identifier: build2

phases:
  install:
    runtime-versions:
      ruby: latest
    commands:
      - pwd

  pre_build:
    commands:
      - gem install bundler
      - bundle install

  build:
    commands:
      - bundle exec rspec
