version: 0.2

batch:
  fast-fail: false
  build-graph:
    - identifier: build1
      env:
        compute-type: BUILD_GENERAL1_SMALL
        buildspec_file: buildspec_test.yml
    - identifier: build2
      env:
        compute-type: BUILD_GENERAL1_SMALL
        buildspec_file: buildspec_test.yml

phases:
  install:
    runtime-versions:
      ruby: latest
    commands:
      - pwd

  pre_build:
    commands:
      - gem install bundler
      - bundle install

  build:
    commands:
      - bundle exec rspec
