version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: build1
    - identifier: build2

phases:
  install:
    runtime-versions:
      ruby: latest
    commands:
      - bundle install

  pre_build:
    commands:

  build:
    commands:
      - bundle exec rspec

  post_build:
    commands:
