version: 0.2

batch:
  fast-fail: false
  build-matrix:
    static:
      ignore-failure: false
    dynamic:
      buildspec:
        - buildspec_test_and_build.yml
      env:
        variables:
          TEST_VARIABLE:
            - AAA
            - BBB

phases:
  install:
    runtime-versions:
      ruby: latest
    commands:
      - pwd
      - env|grep TEST

  pre_build:
    commands:
      - gem install bundler
      - bundle install

  build:
    commands:
      - bundle exec rspec
