version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 30
    commands:
      - echo "BUILD2"
      - pwd
      - env|grep TEST
      - git diff

  pre_build:
    commands:
      - gem install bundler
      - bundle install

  build:
    commands:
      - bundle exec rspec

artifacts:
  files:
    - "**/*"
