version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: tests1
    - identifier: tests2

phases:
  install:
    runtime-versions:
      ruby: 2.7

  build:
    commands:
      - docker build -t sample_rails_app:${CODEBUILD_RESOLVED_SOURCE_VERSION} .

artifacts:
  exclude_path
