version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - pwd
      - echo "Deploying to STAGING"
      - git diff

  build:
    commands:
      - echo "Tests stage!"
