version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7

  build:
    commands:
      - docker build -t sample_rails_app:${CODEBUILD_RESOLVED_SOURCE_VERSION} .
      - echo "repository-name" > docker-image-to-deploy.txt

artifacts:
  files:
    - docker-image-to-deploy.txt
