version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: build1
      buildspec: buildspecs/build1.yml
    - identifier: build2
      buildspec: buildspecs/build2.yml

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - echo "I'm alive!"
      - pwd
      - git diff

  pre_build:
    commands:
      - gem install bundler
      - bundle install

  build:
    commands:
      - bundle exec rspec

artifacts:
  files:
    - "**/*"
