version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - aws sts get-caller-identity
      - aws kms describe-key --key-id arn:aws:kms:eu-west-1:487483287434:key/ec84f810-ec41-45a0-ad9e-3575324d26c4
      - apt-get update
      - apt-get install -yq sops

  build:
    commands:
      - echo "repository-name" > docker-image-to-deploy.txt

artifacts:
  files:
    - docker-image-to-deploy.txt
    - buildspecs/**/*
