version: 0.2

batch:
  fast-fail: false
  static:
    ignore-failure: true
  dynamic:
    buildspec:
      - buildspecs/test-stage-1.yml
      - buildspecs/test-stage-2.yml

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - pwd
      - echo "I'm alive!"
      - git diff

  pre_build:
    commands:
      - gem install bundler
      - bundle install

  build:
    commands:
      - bundle exec rspec

artifacts:
  files:
    - "**/*"
