version: 0.2

batch:
  build-matrix:
    static:
      ignore-failure: true
    dynamic:
      buildspec:
        - buildspecs/test-stage.yml
      env:
        variables:
          TEST_VARIABLE:
            - abc
            - cde

phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - pwd
      - echo "I'm alive!"
      - git diff

  build:
    commands:
      - echo "Tests stage!"

artifacts:
  files:
    - "**/*"
