check_name: 'Rubocop Results'

versions:
  - rubocop: '0.76.0'
  - rubocop-airbnb: '3.0.2'
  - rubocop-rspec: '1.30.1'

rubocop_force_exclusion: true

check_scope: 'modified'
base_branch: 'origin/master'
