name: semgrep-rules-test

on: [push]

jobs:
  test-latest:
    runs-on: ubuntu-latest
    name: test-latest
    steps:
    - uses: actions/checkout@v2
    - name: test-latest
      id: test-latest
      uses: returntocorp/semgrep-rules-test-action@master
