name: Brakeman

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: install brakeman
      run: bundle install

    - name: run brakeman
      run: brakeman sample_rails_app

