name: Brakeman

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: use-ruby 2.7
      uses: ./
      with:
        ruby-version: '2.7'

    - name: install brakeman
      run: gem install brakeman

    - name: run brakeman
      run: brakeman --except Render,VerbConfusion

