name: Brakeman

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: use-ruby 3.0.2
      uses: ./
      with:
        ruby-version: '3.0.2'

    - name: install brakeman
      run: gem install brakeman

    - name: run brakeman
      run: brakeman --except Render,VerbConfusion

